
FROM node:latest As builder

WORKDIR /usr/src/app

COPY ["client/PsuHistory-Front/package*.json", "./"]
RUN npm install

COPY ["client/PsuHistory-Front", "./"]

EXPOSE 4200
# Serve the app
CMD ["npm", "run", "start"]

#FROM node:alpine
#
#WORKDIR /usr/src/app
#
#COPY package.json .
#COPY package-lock.json .
#
#RUN npm install
#
#COPY . .
#
#EXPOSE 4200
#
#CMD /usr/src/app/node_modules/.bin/ng serve --host 0.0.0.0 --disableHostCheck