version: "3.9"

services:
  psuhistory.web:
    container_name: "web"
    environment: 
      Test: "Test"
    build:
      context: ${PATH_DOCKERFILE_FRONT}
      dockerfile: ${NAME_DOCKERFILE_FRONT}
    ports: 
      - "4200:80"    
    depends_on: 
      - "psuhistory.api"

  psuhistory.api:
    container_name: "api"
    environment:
      ASPNETCORE_URLS: "http://+:6700"
    build:
      context: ${PATH_DOCKERFILE_BACK}
      dockerfile: ${NAME_DOCKERFILE_BACK}
    ports: 
      - "6700:6700"
    restart: always
    depends_on: 
      - "psuhistory.database"

  psuhistory.database:
    container_name: "database"
    extends:
      file: ${FILE_DATABASE}
      service: mssql_database

#  psuhistory.database.postgresql:
#    container_name: "postgresql.database"
#    extends:
#      file: database/docker-compose.postgresql.yml
#      service: postgresql_database
#
#  psuhistory.database.pgadmin:
#    container_name: "pgadmin.database"
#    extends:
#      file: database/docker-compose.postgresql.yml
#      service: pgadmin
#
#  psuhistory.database.mysql:
#    container_name: "mysql.database"
#    extends:
#      file: database/docker-compose.mysql.yml
#      service: mysql_database