#ПОДДОМЕН
#l.paranovich@psu.by
version: "3.9"  # optional since v1.27.0

services:
  psuhistory.web:
    container_name: "web"
    environment: 
      NODE_ENV: "production"
    build:
      context: ${PATH_DOCKERFILE_FRONT}
      dockerfile: ${NAME_DOCKERFILE_FRONT}
    ports: 
      - "4200:80"    
    depends_on: 
      - "psuhistory.database"
      - "psuhistory.api"

  psuhistory.api:
    container_name: "api"
    environment:
      DatabaseServer: "database"
      DatabasePort: "1433"
      DatabaseUser: "SA"
      DatabasePassword: "Pa55w0rd2021"
      DatabaseName: "psuhistorydb"
    build:
      context: ${PATH_DOCKERFILE_BACK}
      dockerfile: ${NAME_DOCKERFILE_BACK}
    ports: 
      - "6777:6777"
    restart: always
    depends_on: 
      - "psuhistory.database"

  psuhistory.database:
    container_name: "database"
    extends:
      file: ${FILE_DATABASE}
      service: mssql_database

#  psuhistory.database.postgresql:
#    container_name: "postgresql.database"
#    extends:
#      file: database/docker-compose.postgresql.yml
#      service: postgresql_database
#
#  psuhistory.database.pgadmin:
#    container_name: "pgadmin.database"
#    extends:
#      file: database/docker-compose.postgresql.yml
#      service: pgadmin
#
#  psuhistory.database.mysql:
#    container_name: "mysql.database"
#    extends:
#      file: database/docker-compose.mysql.yml
#      service: mysql_database