version: "3.9"  # optional since v1.27.0

services:

  psuhistory.web:
    container_name: "web"
    image: application.web
    build:
      context: .
      dockerfile: client/Dockerfile
    ports: 
      - "4200:4200"
    depends_on: 
      - "psuhistory.database"
      - "psuhistory.api"

  psuhistory.api:
    container_name: "api"
    image: application.api
    environment:
      DatabaseServer: "database"
      DatabasePort: "1433"
      DatabaseUser: "SA"
      DatabasePassword: "Pa55w0rd2021"
      DatabaseName: "psuhistorydb"
    build:
      context: .
      dockerfile: server/Dockerfile
    ports: 
      - "6777:80"
    restart: always
    depends_on: 
      - "psuhistory.database"

  psuhistory.database:
    container_name: "database"
    extends:
      file: database/docker-compose.mssql.yml
      service: mssql_database

#  psuhistory.database.postgresql:
#    container_name: "postgresql.database"
#    extends:
#      file: database/docker-compose.postgresql.yml
#      service: postgresql_database
#
#  psuhistory.database.pgadmin:
#    container_name: "pgadmin.database"
#    extends:
#      file: database/docker-compose.postgresql.yml
#      service: pgadmin
#
#  psuhistory.database.mysql:
#    container_name: "mysql.database"
#    extends:
#      file: database/docker-compose.mysql.yml
#      service: mysql_database