version: "3.9"

services:
 
  mssql_database:
    container_name: "mssql"
    image: "microsoft/mssql-server-windows-express:${MSSQL_WINDOWS_TAG}"
    environment:
      ACCEPT_EULA: "${ACCEPT_EULA:-Y}"
      SA_PASSWORD: "${SA_PASSWORD:-Pa55w0rd2021}"
    ports:
      - "1433:1433"
    restart: always