version: "3.9"  # optional since v1.27.0

services:
 
  postgresql_database:
    container_name: postgresql
    image: "postgres:${POSTGRESQL_TAG}"
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-admin}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-admin1234}"
      POSTGRES_DB: "${POSTGRES_DB:-psuhistorydb}"
    ports:
      - "5432:5432"
    restart: always
    #volumes:
    #  - database-data:/var/lib/postgresql/data/
     
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD:-admin1234}"
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: always
    #volumes:
    #  - pgadmin:/root/.pgadmin
 
#volumes:
#  database-data:
#  pgadmin: