version: "3.9"

services:
  
  mssql_database:
    container_name: "mssql"
    image: "mcr.microsoft.com/mssql/server:${MSSQL_LINUX_TAG}"
    environment:
      ACCEPT_EULA: "${ACCEPT_EULA:-Y}"
      SA_PASSWORD: "${SA_PASSWORD:-Pa55w0rd2021}"
      MSSQL_PID: "${MSSQL_PID:-Express}"
    ports:
      - "1433:1433"
    restart: always