version: "3.9"

services:
 
  mysql_database:
    container_name: mysql
    image: "mysql:${MYSQL_TAG}"
    environment: 
       MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
       MYSQL_USER: "${MYSQL_USER:-admin}"
       MYSQL_PASSWORD: "${MYSQL_PASSWORD:-admin1234}"
       MYSQL_DATABASE: "${MYSQL_DATABASE:-psuhistorydb}"
    ports:
      - "3307:3306"
    restart: always